M48
; DRILL file {KiCad 9.0.5} date 2025-10-22T22:21:07-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-22T22:21:07-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X-15.0Y9.0
X-15.0Y2.0
X0.0Y9.0
X0.0Y2.0
X15.0Y9.0
X15.0Y2.0
T2
X-25.0Y30.0
X-25.0Y5.0
X25.0Y30.0
X25.0Y5.0
M30
